name: test

on:
  push:
    branches:
      - main

jobs:
  run_code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install 'jira[cli]'
          python -m pip install python-dotenv

      # - name: Get all commit messages
      #   run: |
      #     COMMIT_MESSAGES=$(git log -1 --pretty=%B)
      #     echo "COMMIT_MESSAGES=$COMMIT_MESSAGES" >> $GITHUB_ENV
      - name: Get all commit messages
        run: |
          COMMIT_MESSAGES=$(git log --pretty=%B)
          echo "COMMIT_MESSAGES=$COMMIT_MESSAGES" >> $GITHUB_ENV

      - name: Run main.py
        run: python main.py
        env:
          TOKEN: ${{ secrets.JIRA_TOKEN }}
