name: test

on:
  push:
    branches:
      - main

jobs:
  run_code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install 'jira[cli]'

      - name: Print Jira issue description
        run: |
          from jira import JIRA
          jira = JIRA(server="https://jiracloud.cit.com.br/", token_auth=JIRA_TOKEN) 
          issue = jira.issue("GOPS-3098")
          print(issue.fields.description)
        env:
          TOKEN: ${{ secrets.JIRA_TOKEN }}

